LICENSE
src/deserialize/mod.rs
src/main.rs
src/send/mod.rs
src/send/test.rs
src/settings/mod.rs
src/settings/test.rs

chore(project): add the MPL

---

src/auth_db/mod.rs
src/auth_db/test.rs

Extracted from #28. Depends on #29.

feat(db): implement AuthDb::create_bounce

---

src/providers/mod.rs
src/send/mod.rs

Spotted a few more of these just as I was about to start on a new branch, wanted to pull them out of that PR.

chore(code): eliminate some if-lets in favour of combinators

---

Cargo.lock
src/auth_db/mod.rs
src/bounces/mod.rs
src/bounces/test.rs
src/duration/mod.rs
src/providers/mod.rs
src/providers/sendgrid.rs
src/queues/mod.rs
src/queues/sqs/mod.rs
src/send/mod.rs
src/send/test.rs
src/service_main.rs
src/settings/mod.rs
src/settings/test.rs

Fixes #49 
Send test are failing at the moment, but ready for review.
r? @philbooth @vladikoff 
Co-authored-by: Philip Jenvey <pjenvey@underboss.org>

fix(config): inject config in rocket managed state

---

.circleci/config.yml
Dockerfile

Fixes #47
Rebranched  https://github.com/mozilla/fxa-email-service/pull/64

Setup Circle CI to create docker images

---

CHANGELOG.md
Cargo.lock
Cargo.toml
RELEASE.md

An initial release to sync up with the rest of the projects. The steps are a bit manual
I looked at more automation with https://github.com/sunng87/cargo-release but not done yet.

Release v1.115.0

---

RELEASE.md

chore(docs): improve release doc

---

config/default.json
config/dev.json

chore(config): change aws region defaults for dev and prod

---

Cargo.lock
Cargo.toml
src/bin/queues.rs

See discussion #172 
@seanmonstar thanks for telling us how to fix this :)
r? @vladikoff @philbooth

fix(queues): fix executor error on queues process

---

src/app_errors/mod.rs
src/bounces/mod.rs
src/bounces/test.rs

Fixes #157 
r? @philbooth @vladikoff

feat(errors): return bouncedAt field in bounce error message

---

API.md

feat(docs): document errors and errno

---

README.md

Some of the info in the readme had gone stale, so I updated it. And because I'm OCD about uniformity, I made the build badge for CircleCI look the same as the others.

chore(docs): update the readme

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Merge train-124 into master

---

.travis.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/providers/mod.rs
src/providers/test.rs
src/types/error/mod.rs
src/types/headers/mod.rs
src/types/headers/test.rs

Merge train-125 into master

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/types/error/mod.rs

@philbooth filing so we don't forget

Uplift Train 125 to master

---

src/db/core/mod.rs

@philbooth i keep seeing this warning, this seems unused, confirm?

fix(db): remove unused DataType

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Merge train-126 into master

---

scripts/release.sh

Fixes #252.
Sorry, I didn't tag this repo yesterday, been meaning to get this fixed first.

fix(scripts): ignore merge commits when generating changelog

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Merge train-127 into master

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Merge train-130 into master
