- .rustfmt.toml
- Cargo.lock
- Cargo.toml
- src/main.rs
- src/send/mod.rs
- src/send/test.rs
Fixes #1.
Not wired in to any behaviour, just does some crude validation and then returns a hard-coded message id. There is some test coverage, but also some gaps where I haven't figured out how we should do stuff yet:
* The validation code is punishingly verbose. I evauated a couple of crates to implement validation, `accord` and `validator`, and opted for `validator`. However they both seem quite simple, for instance there's no support for nested objects or values packed inside arrays. This meant we couldn't lean on the nice, readable macro syntax that's available and have to explitly validate fields using Rocket's `FromData` trait instead.
* Rocket has a feature called error catchers, which I couldn't get to work. These are supposed to let you return custom error data but, no matter …
> feat(api): implement a basic /send endpoint

- .gitignore
- Cargo.lock
- Cargo.toml
- config/default.json
- src/main.rs
- src/send/mod.rs
- src/settings/mod.rs
- src/settings/test.rs
Imitates, as closely as possible, the convict-based approach we use in our node repos. The major difference is that validation here has to happen in the code, we can't define it in config.
Settings are applied in the following order:
* `config/default.json`
* `config/${NODE_ENV}.json` (optional)
* `config/local.json` (optional, git-ignored)
* environment variables
I opted to re-use `$NODE_ENV` instead of some rust-specific environment variable so that our dev setups will work with minimal changes. One less environment variable to manage feels like a win to me but if it seems too weird I can change it.
Uses the `config` crate, which was the convictiest dependency I could find.
Initially I was going to include this in the changeset for #2, but it seems worthy of code review in its own right …
> feat(config): add configuration

- config/default.json
- src/deserialize/mod.rs
- src/main.rs
- src/settings/mod.rs
- src/settings/test.rs
Fixes #13, opened as an alternative to #14 so that it can be r+'ed if it turns out to be the preferred option.
Extracts the inline validation code from the settings module to a dedicated deserialize module, so that the validation rules can be better re-used elsewhere.
Uses functions rather than newtype structs, for 2 reasons:
1. There's an issue in the config crate where newtype structs aren't deserialized. An unmerged PR exists to fix it, but in the meantime this changeset works round the problem.
2. With newtype structs, the tests aren't able to create fresh instances of the `Settings` struct unless it is flattened to a single level.
If we do pursue this approach, we can revisit using newtype structs down the line when both of the above are resolved.
> refactor(settings): extract common functions for deserialization

- Cargo.lock
- src/auth_db/mod.rs
- src/auth_db/test.rs
- src/bounces/mod.rs
- src/bounces/test.rs
When I did #22, I didn't pay much attention to the `emailBounces` table because there weren't any rows in my table locally. But it quickly became obvious while implementing #5 that I was missing some columns as well as a valid value for the `BounceType` enum.
This changeset fixes both of those issues and includes a couple of other nearby tweaks taken from the same branch, so that I can bring the size of that PR down a bit (it's a beast).
> fix(db): add missing fields/values to auth_db::BounceRecord

- src/auth_db/mod.rs
- src/auth_db/test.rs
Extracted from #28.
I was missing some tests for `BounceSubtype` deserialization, which meant I hadn't realised that the derived implementation of `Deserialize` was mapping values to strings rather than numbers. This change fixes that and adds the corresponding test coverage.
> fix(db): fix broken BounceSubtype deserialization

- src/auth_db/mod.rs
Extracted from #28.
External error types seem to print the most helpful information via the `Debug` trait, which can be accessed using the `{:?}` format specifier. This change just ensures we propagate that more useful information when wrapping other error types.
> fix(errors): include more useful messages in wrapping errors

- src/app_errors/mod.rs
It was annoying me that our error payloads include explicit `nulls`, then over the weekend I spotted this fix in someone else's code. Works well, although I couldn't figure out how to write tests for it because we get the `ApplicationError` type back there, rather than the raw JSON string.
Before:
```
~/c/fxa-email-service (master) $ curl -d '{"subject":"bar","body":{"text":"baz"}}' -H 'Content-Type: application/json' http://localhost:8001/send
{"status":400,"error":"Bad Request","errno":null,"message":null,"data":null}
```
After:
```
~/c/fxa-email-service (pb/strip-nulls-from-errors) $ curl -d '{"subject":"bar","body":{"text":"baz"}}' -H 'Content-Type: application/json' http://localhost:8001/send
{"status":400,"error":"Bad Request"}
```
> chore(errors): don't serialize nulls in error payloads

- src/validate/mod.rs
- src/validate/test.rs
email address validation is a pain, and you can use a surprising variety
of characters in an address.
(At least we're drawing the line at no quoted characters...)
Closes #44
> bug: allow RFC5321 compliant email addresses

- src/validate/mod.rs
- src/validate/test.rs
I thought this might have been too restrictive and it was. I didn't listen to myself though, did I?
@brizental, this should let your Sendgrid API key pass validation. r?
(and @fxa-devs r?)
> fix(validation): relax the sendgrid API key validation regex

- Cargo.lock
- Cargo.toml
Whoops, should have remembered this when reviewing #57, we can't use futures 0.2 yet so this pins it to the 0.1 family. (running `cargo update` then `cargo t` without this change will fail)
> chore(project): limit futures to < 0.2

- src/send/mod.rs
- src/service_main.rs
Fixes #41.
Since we got the sprauncy new regex in #45, I decided to quickly whip out this dependency right away. It's been annoying me for a while.
> chore(project): remove the validator dependency

- src/bounces/mod.rs
- src/bounces/test.rs
Fixes #56.
We were indiscriminately converting all bounce errors to a 429 response. This changes it so we only return the 429 if the error has a bounce record, otherwise we return a 500.
> fix(bounces): ensure db errors don't get converted to 429 responses

- Cargo.lock
- config/default.json
- src/deserialize.rs
- src/settings/mod.rs
- src/settings/test.rs
- src/validate/mod.rs
- src/validate/test.rs
Fixes #61 .
Not much to talk about here, just deleted the settings and adjusted the tests.
The `Cargo.lock` file was updated as well, I think that's because some of the crates were updated. Since we got `>=` in the cargo versions right now, I think when crates are updated we just grab the new versions on `cargo build`, thus updating the `Cargo.lock` file.
Anyways, r? @philbooth @vladikoff
> refactor(service): remove smtp settings

- Cargo.lock
- Cargo.toml
- src/bin/queues.rs
- src/bin/service.rs
- src/lib.rs
Fixes #76.
All of the code is now compiled into a common `fxa_email_service` lib, which the `service` and `queues` binaries link to. In terms of running the tests and executing the binaries, nothing has really changed. But it should mean we don't get any more dead code warnings.
No rush to review, it can wait until after the All Hands.
> refactor(project): push core code into a common lib

- src/auth_db/mod.rs
- src/bounces/mod.rs
- src/bounces/test.rs
- src/queues/mod.rs
Fixes #68.
We don't want to let knowledge about the auth db leak into any unrelated application logic, because it's both temporary and in possession of capabilities that this repo has no business knowing about.
> refactor(db): hide queues db access behind bounces interface

- src/message_data/mod.rs
- src/message_data/test.rs
- src/queues/mod.rs
- src/queues/notification.rs
- src/queues/sqs/notification/mod.rs
Depends on #72. Fixes #4.
Adds the ability to consume stored metadata from Redis and add it to the outgoing notification.
Again, no rush to review this, it can wait until after the All Hands.
> feat(metadata): send message metadata in outgoing notifications

- src/queues/notification.rs
- src/queues/sqs/mod.rs
- src/queues/sqs/notification/mod.rs
Fixes #6. Fixes #90.
There are ~~two~~ three fixes here:
* In 13ea68f, I fix a really stupid piece of code that means parsing always fails for queue notifications.
* In 12361e2, I make a bunch of fields in the `Notification` type optional, so that we can synthesize them from Sendgrid events without having to invent dummy data. It's not stuff we're actually using anyway, so it could have been optional already.
* In 8fa51ec, I fix another really stupid piece of code where it was trying to deserialize `bouncedRecipients` using the wrong name.
There are no test changes because we don't have proper test coverage for the SQS stuff yet, which probably contributed to my mistake for the first fix. But writing those tests is a bigger piece of work and landing this in the meantime means I can …
> fix(queues): parse notifications synthesized from sendgrid events

- src/app_errors/mod.rs
- src/app_errors/test.rs
- src/auth_db/mod.rs
- src/auth_db/test.rs
- src/bin/service.rs
- src/bounces/mod.rs
- src/bounces/test.rs
- src/lib.rs
- src/providers/mock.rs
- src/providers/mod.rs
- src/providers/sendgrid.rs
- src/providers/ses.rs
- src/queues/mod.rs
- src/send/mod.rs
- src/send/test.rs
Connects to #48 
I had to change basically everything since my last PR (#85) about this, so I thought it would be best to just create a new PR.
To  get the failure errors working I needed to get at least `providers`, `bounces` and `db` to also work with the failure errors, not just the Rocket and HTTP errors. That's what I'm doing in this PR. Since this is kind of a big change, I thought it would be best to send this in before adapting the tests to the new error type, so, right now, many tests are commented.
Let me know what you guys think. If you think this is a good change I still would need to adapt all tests and also there are some error types specially for the queues bin that need to be changed as well.
I personally think this is a good change. It is abstracting all the errors to one …
> refactor(errors): use failure crate to handle errors

- config/default.json
- config/dev.json
- config/test.json
- scripts/test_standalone.sh
- scripts/test_with_authdb.sh
- src/logging/mod.rs
- src/settings/mod.rs
Fixes #82 
When we are in a testing environment (which means when `NODE_ENV=test`) the logger won't show anything. 
So now, instead of having `mozlog:true | false` in the config, we have `logging: null | pretty | mozlog`.
r? @vladikoff
> feat(logging): add null logger for testing environment

- Rocket.toml
- src/settings/mod.rs
Fixes #100 
Fixes #24 
As mentioned in #24 we still need to see about `ROCKET_WORKERS`.
Also, in production, rocket sends a warning about not having set a secret_key, but I decided to leave it without anything for now. Anyways that would be something that probably we wouldn't "hard code" here.
r? @vladikoff @philbooth
> chore(settings): prepare prod and stage configs for deployment

- config/default.json
- src/message_data/mod.rs
- src/message_data/test.rs
- src/settings/mod.rs
- src/settings/test.rs
Fixes #109 
Because we had underscores in the name of this setting, it wasn't getting overwritten by an `FXA_EMAIL_` environment variable. At first I thought this was a bug with `config-rs` but it actually looks like a design choice, because they use underscores to signal nesting. For example:
```
"authdb": {
"baseuri": "http://127.0.0.1:8000/"
}
```
Will get overwritten by the environment variable `FXA_EMAIL_AUTHDB_BASEURI`.
Anyways, to fix this I changed the `message_id_hmac_key` setting to not have any underscores. Since that was too long for just removing the underscores, I did a little nesting for the resulting environment variable to look nicer. Now, to overwrite the hmac key we can just use `FXA_EMAIL_MESSAGEDATA_HMACKEY`.
I also added that to our settings tests, so that we can …
> fix(settings): get message data hmac key setting to work with env variables

- Cargo.toml
- Dockerfile
- README.md
- r
- scripts/run_queues.sh
- scripts/run_send.sh
- scripts/run_service.sh
- src/app_errors/mod.rs
- src/auth_db/mod.rs
- src/bin/queues.rs
- src/bin/service.rs
- src/bounces/mod.rs
- src/deserialize/mod.rs
- src/duration/mod.rs
- src/lib.rs
- src/logging/mod.rs
- src/message_data/mod.rs
- src/providers/mod.rs
- src/queues/mod.rs
- src/queues/notification.rs
- src/queues/sqs/mod.rs
- src/queues/sqs/notification/mod.rs
- src/send/mod.rs
- src/serialize/mod.rs
- src/settings/mod.rs
- src/validate/mod.rs
Fixes #51.
Adds a bunch of doc comments for use with `rustdoc`. You can try it out locally by running:
```
cargo doc --no-deps --open
```
It should open something like this in your browser:
If this gets a green-light, I'll also create a GitHub Pages branch so that we can refer/link to a hosted version of the docs without needing to build them locally.
> feat(docs): generate developer docs with rustdoc

- src/settings/mod.rs
A couple of small documentation fixes, not associated with any issue:
* Add a docstring to the `derive_and_validate` macro expansion. All the other types in `settings` have a doc comment and the generated docs looked incomplete without it for these too.
* Fix up the docs for `SqsUrls`, introducing a newline to keep the outer summary short and moving another note up from the wrong place where it was associated with `SqsUrls::bounce`.
With these changes, the `settings` docs look like this:
@brizental, @mozilla/fxa-devs r?
> fix(docs): better docs for the settings module

- src/email_address/mod.rs
- src/email_address/test.rs
- src/lib.rs
- src/send/mod.rs
- src/send/test.rs
- src/settings/mod.rs
@brizental, I changed my mind and decided to do this straight away. The thing that persuaded me was when looking at the docs after merging your PR, `EmailAddress` seemed a bit out-of-place and surprising listed under the `send` module:
> refactor(types): extract the EmailAddress type to its own module

- Cargo.lock
- Cargo.toml
- Rocket.toml
- src/app_errors/mod.rs
- src/bin/service.rs
- src/bounces/test.rs
- src/lib.rs
- src/send/mod.rs
- src/send/test.rs
Fixes #111 
In order to do this I had to point our rocket version to the Rocket repo and that introduced some breaking changes which I also fixed in this PR. Mostly they were variable name changes 👍 
Anyways now if you run rocket right `ROCKET_ENV=production` you get no rocket logs.
r? @vladikoff @philbooth
> feat(logging): turn off rocket logs for production

- Dockerfile
This version.json must be included for the dockerflow to verify to image, so it will require a v1.116.1 tag too.
r? - @philbooth, @vladikoff
> fix(docker): include /app/version.json in final image (dockerflow required)

- .travis.yml
- Cargo.lock
- Dockerfile
- src/settings/mod.rs
Fixes #130.
We don't want the regular cycle of conflicts between Rust nightlies and (usually) rocket codegen to affect us in prod. And, funnily enough, the version that I first tried pinning to contains one of those of conflicts, so good reminder there. (nightly 2018-07-15 works with Rocket 0.3.15, but we're pinned to a specific commit on master for now)
So this pins to nightly 2018-07-14, and also includes a `cargo update`, and also changes some code in `src/settings/mod.rs` because of an API change in the `config` crate.
> fix(deploy): pin to a known compatible rust version in docker and ci

- Cargo.lock
- Cargo.toml
- src/app_errors/mod.rs
- src/bounces/mod.rs
- src/providers/mod.rs
- src/providers/sendgrid.rs
- src/providers/ses.rs
- src/providers/ses/mod.rs
- src/providers/ses/test.rs
- src/providers/smtp.rs
- src/providers/test.rs
Fixes #21 
Gets all these done: https://github.com/mozilla/fxa-email-service/issues/21#issuecomment-402312872 
I put the mime message building as a default for the `Provider` trait because it is not something exclusive to the SES provider and might be useful for other providers we might implement in the future and it made it easier for testing.
Also, I removed the underline from all error properties, there was no reason for them to be there and it made it more confusing because it seemed like they had the underline because they were not being used... Let me know if you guys think that should be extracted into it's own PR.
Anyways, r? @philbooth @vladikoff
> chore(tests): add tests for ses provider and mime message building

- Dockerfile
Docker image build fails without removing this line.
> fix(docker): Rocket.toml no longer exists, so don't copy it

- Dockerfile
- config/default.json
- config/dev.json
- config/test.json
- scripts/test_standalone.sh
- scripts/test_with_authdb.sh
- src/logging/mod.rs
- src/settings/mod.rs
- src/settings/test.rs
- src/validate/mod.rs
- src/validate/test.rs
Fixes #138 
Connects to #139 
I did this in two different commits on purpose, so that if we wanna keep using `NODE_ENV` we can remove all the code that removes it by resetting to the first commit in this PR. By the way, I had it default to `dev` in case `FXA_EMAIL_ENV` is not set, I'm not sure this is expected behaviour.
Anyways, I added the `FXA_EMAIL_LOG_LEVEL` variable and changed the `FXA_EMAIL_LOGGING` one to `FXA_EMAIL_LOG_FORMAT`. That is getting a little confusing in my opinion, though. This is what is happening right now:
- `FXA_EMAIL_LOG_LEVEL` : sets the rocket logging level, and does nothing to our logs.
- `FXA_EMAIL_LOG_FORMAT`: sets our logs formatting style. One of the options is `null`, though. Which depending on how you look at it, is a logging level and not formatting. …
> refactor(settings): drop NODE_ENV and add LOG_LEVEL

- config/default.json
- src/settings/mod.rs
- src/settings/test.rs
Fixes #146 
When I changed to use `Rocket::custom` instead of `Rocket.toml` for creating configuration, I forgot about `ROCKET_SECRET_KEY`. 
It's good to note that, because we are using `Rocket::custom` none of the `ROCKET_` env vars will work, so if ever we need to set any of the fields in config, we need to add to our config and to our rocket config builder function. 
These are the possible fields in rocket config: https://api.rocket.rs/rocket/config/struct.ConfigBuilder.html#fields
r? @philbooth @jrgm @vladikoff
> feat(settings): add rocket secret_key to settings

- config/default.json
- config/dev.json
- src/providers/mod.rs
- src/providers/test.rs
- src/send/test.rs
- src/settings/mod.rs
- src/settings/test.rs
Over in https://github.com/mozilla/fxa-auth-server/pull/2535, work is being done to enable the auth server to specify the provider for specific requests. I think this will cause a problem in local dev because we always want to use the local `smtp` provider there, right?
As a hackish approach to resolving that conflict, this change introduces a new boolean setting called `forceprovider`. If `forceprovider` is `true`, the default provider may not be overridden by individual requests.
Maybe there's a less hackish approach though. Any suggestions?
> feat(settings): enable the default provider to override requests

- src/providers/ses/test.rs
- src/send/test.rs
- src/validate/mod.rs
- src/validate/test.rs
Fixes #9 
I just added some simple unicode tests for email address, subject and body.
I also added unicode character patterns in our email address regex, because the `.` alone didn't match for some reason...
r? @philbooth @vladikoff
> chore(tests): add tests for request unicode handling

- .travis.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- src/auth_db/mod.rs
- src/auth_db/test.rs
- src/bin/queues.rs
- src/bounces/mod.rs
- src/bounces/test.rs
- src/message_data/mod.rs
- src/providers/mod.rs
- src/providers/sendgrid.rs
- src/providers/ses/mod.rs
- src/providers/ses/test.rs
- src/providers/socketlabs.rs
- src/queues/mod.rs
- src/queues/sqs/mod.rs
- src/send/mod.rs
- src/send/test.rs
Fixes #156 
Fixes #158 
Here I update failure, rocket, rusoto and rust to the latest versions.
I had to point rusoto to a revision, because `rusoto_mock` stopped working after the update. I opened an issue about that https://github.com/rusoto/rusoto/issues/1089.
Because I updated the rust version, there are a bunch of formatting changes in this PR, because fmt was updated as well.
r? @philbooth @vladikoff 
_ps.: when this gets merged we can't forget to change the override in `fxa-local-dev` https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/install_all.sh#L42_
> chore(deps): update rocket, failure, rusoto and rust versions

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/providers/socketlabs.rs
Turns out we can manually add a message id to socketlabs requests.
See more discussion in https://github.com/mozilla/fxa-sendgrid-event-proxy/pull/3#discussion_r209323789
r? @philbooth @vladikoff
> feat(socketlabs): create and return id for socketlabs messages

- README.md
This service is now live in production, so we can probably remove the under construction badge.
> chore(docs): remove under construction badge

- Cargo.lock
- Cargo.toml
- src/bin/queues.rs
- src/bin/service.rs
- src/lib.rs
- src/logging/mod.rs
- src/settings/mod.rs
- src/settings/test.rs
- src/validate/mod.rs
- src/validate/test.rs
Fix #155 
I added support for Sentry. For that to work we just need to set `FXA_EMAIL_SENTRY_DSN`.
Right now we are logging to Sentry everytime we log an `AppError`.
r? @vladikoff
> feat(logging): add sentry support

- src/lib.rs
- src/queues/sqs/mod.rs
This is just a follow up PR from #177 
I remove the part where I make the parser work for different SNS message formats, turns out that is not needed. 
See discussion: https://github.com/mozilla/fxa-email-service/pull/177#issuecomment-414394797
r? @vladikoff
> fix(queues): make queue parsing logic follow the sns format

- Cargo.toml
- src/queues/sqs/notification/test.rs
- src/queues/sqs/notification/test_notifications.json
Connects to #162 
I started working on this issue, but I'm not really sure I'm doing the right thing. I'm submitting this work in progress so that you can check that this is the kind of tests needed, @philbooth . I started the code for the tests, but before finishing it I just wanted to check, because it looks kind of weird to me...
I also added a commit that updates the config.rs version in the Cargo.toml because we had `0.8.0` there, but turns out we use features from the crate that don't exist in that version only on `>=0.9.0`. That was a problem I stumbled on while working on #162 this is why the commit is in this PR. It was such a small change I didn't think it needed to have a whole PR for itself, but let me know if you want I can do that too.
r? @philbooth
> chore(tests): add tests for message parsing in the queues

- src/queues/sqs/notification/mod.rs
Fixes #189 
Removed everything that is not used anywhere else in the code but the `id`s because I thought that we might need them if ever we need to debug something.
r? @philbooth
> fix(queues): remove unused fields from notification structs

- Cargo.lock
- Cargo.toml
- src/settings/mod.rs
- src/settings/test.rs
Fixes #191.
You can also test it manually by setting, say, `FXA_EMAIL_PORT` to the empty string and running `./r`. Before this change that fails with the error:
```
thread 'main' panicked at 'Settings::new error: invalid type: string "", expected an integer in the environment', libcore/result.rs:983:5
```
> fix(config): ignore empty environment variables

- API.md
- src/app_errors/mod.rs
- src/auth_db/mod.rs
- src/bounces/test.rs
- src/db.rs
- src/healthcheck/mod.rs
- src/lib.rs
- src/message_data/mod.rs
- src/message_data/test.rs
Related to #166.
We've decided to use Redis as the data store for all types in this repo so as a first step towards that, this PR just pulls the redis code out of `message_data` into its own module.
No functionality has changed so no tests are changed. And no new tests are added because the `db` module is going to be tested via its consumers (i.e. the existing `message_data` tests right now, but also `bounces` and `configuration` in the future).
> refactor(redis): extract redis code to a dedicated db module

- .circleci/config.yml
Fixes #195.
Compare, for example, #196 to this PR. There it has kicked off an [unnecessary Circle build](https://circleci.com/gh/mozilla/fxa-email-service/241), here we're only building in Travis.
> fix(ci): only build deployment artifacts for tags

- src/app_errors/mod.rs
- src/auth_db/mod.rs
- src/auth_db/test.rs
- src/bounces/mod.rs
- src/bounces/test.rs
- src/email_address/mod.rs
- src/email_address/test.rs
- src/providers/sendgrid.rs
- src/providers/ses/mod.rs
- src/providers/smtp.rs
- src/providers/socketlabs.rs
- src/queues/mock.rs
- src/queues/notification.rs
- src/queues/sqs/notification/mod.rs
- src/queues/sqs/notification/test.rs
- src/send/mod.rs
- src/settings/test.rs
The EmailAddress type was only being used in some places, which meant some places that weren't using it had to call `validate::email_address` manually. This change spreads it throughout most of the project, so that almost everywhere gets to benefit from strong typing.
The only place I decided to leave alone was the provider layer, where some providers have their own `EmailAddress` struct. I could have aliased it at that layer too, but by that point addresses are just dumb strings anyway so it didn't seem worth it.
(this is an extraction from `pb/166-wip` because that branch is growing too big)
> refactor(types): prefer EmailAddress type to raw strings

- API.md
- src/app_errors/mod.rs
- src/db.rs
- src/message_data/mod.rs
- src/message_data/test.rs
- src/queues/sqs/mod.rs
Related to #166.
Previously, our Redis abstraction only worked with strings because it only dealt with the somewhat nebulous concept of message metadata. Now that we also want to use it for concrete types, it makes sense to bake in automatic serialization from and deserialization to those types. This frees consumers from the responsibility of having to serialize to a Redis-friendly format manually.
This change achieves that aim by making the db methods generic. `db.set` gets a type parameter that is `Serialize` and the getters get one that is `DeserializeOwned`.
(this is the final extraction from `pb/166-wip` before I can open the actual pull request for that change)
> feat(db): serialize to JSON on write and deserialize from JSON on read

- src/db.rs
- src/message_data/mod.rs
- src/message_data/test.rs
- src/queues/mod.rs
This is another extraction from the branch for #166.
Previously, we were treating an absence of data as an error case in Redis. That's wrong for every data type we plan to store, so this PR changes the `db` module to wrap its result types in an `Option`.
> refactor(redis): stop treating no data as an error in the getters

- src/auth_db/mod.rs
- src/db/mod.rs
- src/db/test.rs
- src/delivery_problems/mod.rs
- src/delivery_problems/test.rs
- src/message_data/test.rs
Related to #166.
This is the first step towards migrating away from the FxA auth db. We'll start by dual-writing to both databases. Then, after we've got sufficient history to fully evaluate limit violations using our own data, we can switch over to read from our own datastore and ditch the auth db.
Note that we still need to migrate from the auth server's bounce and complaint handling logic in prod before this code starts doing anything.
> feat(db): write bounce and complaint records to our own db

- src/queues/notification.rs
- src/queues/sqs/notification/test.rs
The `bounced_recipients` property of the outgoing notification structure was missing a serde `rename` attribute. That problem went undetected because we had no test coverage for the outgoing structure, which was a pretty large hole in our coverage. This change fixes the issue and adds some serialization assertions.
> fix(queues): fix the serialized format of outgoing notifications

- src/auth_db/mod.rs
- src/logging/mod.rs
- src/providers/mod.rs
- src/providers/sendgrid.rs
- src/providers/ses/mod.rs
- src/providers/smtp.rs
- src/providers/socketlabs.rs
- src/queues/sqs/mod.rs
- src/queues/sqs/notification/mod.rs
- src/settings/mod.rs
Fixes #211.
For a bunch of types in `src/settings.rs` and for `NotificationType` in `src/queues/sqs/notification/mod.rs`, we were allocating `String` instances when it wasn't always necessary. Where a slice can be used, it's preferable.
At the same time, I removed a load of `.0` inner type access for the newtype structs in `Settings`, because that notation is leaky (if we want to refactor the struct to something else, all the usage must change too).
No actual functionality is changed here, so there are no test changes.
> fix(code): implement AsRef<str> to expose cheaper &str access

- src/api/send/test.rs
- src/db/delivery_problems/test.rs
- src/logging/mod.rs
- src/providers/ses/test.rs
- src/types/error/mod.rs
- src/types/error/test.rs
Related to #210.
There was a minor violation of the law of Demeter in our `AppError` struct, where it was directly exposing its inner `AppErrorKind` to callers. Not a huge deal, but it meant that any changes made to the inner structure would leak out and require corresponding changes to the consuming code (and I am planning some of those inner changes as part of issue #210). Better to expose just the parts that are necessary via its own API.
At the same time, I opted to replace the home-baked `AppError::json()` method with a more conventional `impl Serialize`, because it's less astonishing and just as easy to use with `serde_json::to_string`.
> refactor(errors): stop exposing AppErrorKind directly from AppError

- src/db/delivery_problems/mod.rs
- src/db/delivery_problems/test.rs
- src/queues/mod.rs
Fixes #205.
SES provides a UTC-based timestamp for bounce and complaint events but the auth server opted to ignore it. I'm not sure that was the optimal decision because messages might linger on a queue (either ours or the provider's) for a length of time before we process it. Given that we already trust SES et al to deliver sane notifications, it doesn't seem too great a stretch to also trust the timestamp on those notifications.
> feat(bounces): use timestamps from ses instead of the current time

- src/types/email_address/mod.rs
- src/types/email_address/test.rs
Fixes #201.
Email addresses that we receive from bounce, complaint and delivery notifications may not be identical matches to what we set on messages. We already did some normalization by lower-casing the address when parsing. This change extends that normalization process by trimming whitespace and unwrapping the address part if it has been wrapped in angle bracket delimiters to separate it from the display name. This matches the [behaviour of the auth server](https://github.com/mozilla/fxa-auth-server/blob/050a8a646304313502a31e38cbfffd6b1eabf6cf/lib/email/bounces.js#L65-L87).
> feat(types): ignore display name part when parsing email addresses

- src/bin/queues.rs
- src/bin/service.rs
I'm a fool. Yesterday, when I did #230, I only tested it with Sentry enabled. As soon as I ran the code with Sentry disabled this morning, it crashed on startup because the empty string is not a valid Sentry DSN. This change fixes it by only attempting to parse the DSN if Sentry is enabled. 😊
> fix(settings): fix panic when sentry is disabled

- src/providers/mod.rs
- src/providers/test.rs
- src/settings/mod.rs
- src/settings/test.rs
- src/types/mod.rs
- src/types/provider/mod.rs
- src/types/provider/test.rs
- src/types/validate/mod.rs
- src/types/validate/test.rs
Related to #216.
The provider type was modelled as a newtype struct around a `String` but there's a finite number of values, so really it should be an enum. This wasn't too pressing until now but will shortly come in useful for the configuration stuff, which needs a provider type too.
> feat(settings): extract provider type to a fully-fledged enum

- .travis.yml
- src/providers/mod.rs
- src/providers/test.rs
- src/types/error/mod.rs
- src/types/headers/mod.rs
- src/types/headers/test.rs
Fixes #239.
The missing `charset` in the `Content-Type` header caused train 124 to fail. I could have patched it in 124 but it feels like we're close enough to train 125 to patch it there instead now (and I don't even know if there's ops bandwidth to test it out in 124 again anyway).
I've also added the `Sender` header, although I don't *think* its absence was causing problems. The spec seems pretty clear that it falls back to the value of `From` by default, but email servers are a capricious species so better to be explicit.
The `Content-Language` header can only be patched in the auth server (patch incoming). The `Content-Transfer-Encoding` header is by design.
> fix(ses): ensure html part gets charset=utf-8 content type

- .travis.yml
- src/providers/mod.rs
- src/providers/ses/mod.rs
- src/providers/test.rs
- src/types/headers/mod.rs
- src/types/headers/test.rs
Related to #239.
This is not quite a clean cherry-pick of #240. The train-124 and train-125 branches have diverged significantly in a number of areas so there were conflicts to resolve around the error handling.
> Cherry-pick fixes from v1.125.1 to train-124

- src/types/error/mod.rs
Fixes #244.
I made Sentry too noisy when I did #230. This ensures that only `500` errors show up there.
Opened against train 125 for a point release.
> fix(sentry): stop passing 4xx errors to Sentry

- Cargo.toml
In https://github.com/mozilla-services/syncstorage-rs/pull/91#discussion_r235500761, it was pointed out that `debug = true` is the maximum debug info setting and Sentry can still pull out line numbers if we use a lower level instead. Ergo, `debug = 1`.
> chore(build): lower the debug level to decrease binary size

- src/settings/mod.rs
- src/settings/test.rs
- src/types/env/mod.rs
- src/types/env/test.rs
- src/types/error/mod.rs
- src/types/mod.rs
- src/types/provider/test.rs
- src/types/validate/mod.rs
- src/types/validate/test.rs
Related to #216.
There are a bunch of string settings that should be enums. As a first step to fixing that, here I pull out some common enum boilerplate to an `enum_boilerplate!` macro and use it to implement `Env`, which was previously a wrapped string, and `Provider`, which was already an enum.
I didn't try to fix any of the other settings yet because I thought the macro might be a contentious change. If this gets the green light, it will be straightforward to mop up the remaining settings using the same macro.
> refactor(settings): promote Env to an enum from a wrapped string

- config/default.json
- src/api/healthcheck/test.rs
- src/db/delivery_problems/mod.rs
- src/db/delivery_problems/test.rs
- src/settings/mod.rs
- src/settings/test.rs
This PR renames `BounceLimit(s)` to `DeliveryProblemLimit(s)`, which better describes what the struct is storing since it can contain delivery bounces and complaints.
Fixes #217
> refactor(settings): rename `BounceLimit(s)` to `DeliveryProblemLimit(s)`

- scripts/test_standalone.sh
- scripts/test_with_authdb.sh
- src/api/healthcheck/test.rs
- src/api/send/test.rs
- src/bin/queues.rs
- src/bin/service.rs
- src/logging/mod.rs
- src/settings/mod.rs
- src/settings/test.rs
- src/types/error/mod.rs
- src/types/logging/mod.rs
- src/types/logging/test.rs
- src/types/mod.rs
- src/types/validate/mod.rs
- src/types/validate/test.rs
Related to #216.
As well as creating the two enums, this change removes the `null` setting for `LogFormat`, because we already have `LogLevel::Off` and having two different ways to achieve the same thing seemed like a recipe for confusion.
> refactor(settings): promote LogFormat and LogLevel to enums

- src/types/env/mod.rs
- src/types/logging/mod.rs
- src/types/mod.rs
- src/types/provider/mod.rs
Fixes #216.
The last part of the enum refactoring, since all our enums have a default value we may as well implement `Default` in `enum_boilerplate!` too.
The other thing mentioned for #216 was to use `rusoto_core::Region` but actually it doesn't work so well for us. The serialised format is an array, `[ name, endpoint ]`, whereas we only want to specify the name in our settings. So I figure we can leave it like it is for now and decide whether we want to implement our own `AwsRegion` type later.
> refactor(settings): implement Default in enum_boilerplate!

- README.md
Removes the link to the old feature doc, which contains outdated technical information. Also upgrades "*some* FxA email traffic" to "*all* FxA email traffic", because we're at 100% now.
> chore(docs): minor readme editorialisation

- src/types/mod.rs
- src/types/regex/mod.rs
- src/types/regex/test.rs
Extraction from #258.
The configuration endpoint will have a regex property in the payload, which will also be written to Redis. Since `regex::Regex` doesn't provide implementations of `Deserialize` or `Serialize`, we must wrap it to implement them ourselves. This change does that by just serializing the string representation of the regex.
> feat(types): implement a serializable regex type

- src/types/validate/mod.rs
- src/types/validate/test.rs
Fixes #273.
Same underlying issue as mozilla/fxa-content-server#6702. Typing is hard.
> fix(api): use correct apostrophe character in email address regex
